// <auto-generated />
using System;
using DIMON_APP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DIMON_APP.Migrations
{
    [DbContext(typeof(MyWebApiDbContext))]
    [Migration("20191012132053_AddSensorInfoTable")]
    partial class AddSensorInfoTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("DIMON_APP.Models.Apparatus", b =>
                {
                    b.Property<int>("Id_Ap")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("App_name");

                    b.Property<int?>("Parent_id");

                    b.HasKey("Id_Ap");

                    b.ToTable("Apparatus");
                });

            modelBuilder.Entity("DIMON_APP.Models.SensorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("SensorName");

                    b.HasKey("Id");

                    b.ToTable("sensorInfo");
                });

            modelBuilder.Entity("DIMON_APP.Models.Sensor_vals", b =>
                {
                    b.Property<int>("Value_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Date_time");

                    b.Property<int>("Id_sensor");

                    b.Property<int>("Parent_id");

                    b.Property<string>("Sensor_name");

                    b.Property<float>("Sensor_value");

                    b.HasKey("Value_id");

                    b.ToTable("Sensor_Val");
                });

            modelBuilder.Entity("DIMON_APP.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Last_name");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
